version: "3.9"
services:
  redis:
    image: redis
    ports:
    - "6379:6379"
  import-service:
    ports:
    - "8000:8000"
    build:
      context: .
      dockerfile: ./import-service/Dockerfile
  resource-service:
    build:
      context: .
      dockerfile: ./resource-service/Dockerfile
